### ISSUE TITLE
After file renaming compile fails with 

### ISSUE THREAD

**Issue by Ntemis** [FluBBaOfWard/DoubleDribbleDS#1]
linking DoubleDribbleDS.elf
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: FileHandling.o: in function `loadRoms':
/home/demetris/Desktop/Development/DoubleDribbleDS/source/FileHandling.c:213: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/DoubleDribbleDS/source/FileHandling.c:215: undefined reference to `loadFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/DoubleDribbleDS/source/FileHandling.c:223: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/DoubleDribbleDS/source/FileHandling.c:223: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/DoubleDribbleDS/source/FileHandling.c:225: undefined reference to `loadFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: FileHelper.o: in function `loadROM':
/home/demetris/Desktop/Development/DoubleDribbleDS/source/Shared/FileHelper.c:69: undefined reference to `loadFileTypeInZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/DoubleDribbleDS/source/Shared/FileHelper.c:91: undefined reference to `cenHead'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/DoubleDribbleDS/source/Shared/FileHelper.c:91: undefined reference to `zipFilename'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/DoubleDribbleDS/source/Shared/FileHelper.c:91: undefined reference to `zipError'
collect2: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitARM/ds_rules:54: /home/demetris/Desktop/Development/DoubleDribbleDS/DoubleDribbleDS.elf] Error 1
make: *** [Makefile:114: build] Error 2

**Comment by FluBBaOfWard** [comment]
Pushed new source.

**Comment by Ntemis** [comment]
EmuMenu.c
/home/demetris/Desktop/Development/DoubleDribbleDS/source/Shared/EmuMenu.c: In function 'flickSet':
/home/demetris/Desktop/Development/DoubleDribbleDS/source/Shared/EmuMenu.c:793:9: error: 'g_flicker' undeclared (first use in this function); did you mean 'gFlicker'?
  793 |         g_flicker++;
      |         ^~~~~~~~~
      |         gFlicker
/home/demetris/Desktop/Development/DoubleDribbleDS/source/Shared/EmuMenu.c:793:9: note: each undeclared identifier is reported only once for each function it appears in
/home/demetris/Desktop/Development/DoubleDribbleDS/source/Shared/EmuMenu.c:796:17: error: 'g_twitch' undeclared (first use in this function); did you mean 'gTwitch'?
  796 |                 g_twitch = 0;
      |                 ^~~~~~~~
      |                 gTwitch
make[1]: *** [/opt/devkitpro/devkitARM/base_rules:85: EmuMenu.o] Error 1
rm EmuFont.s
make: *** [Makefile:114: build] Error 2

**Comment by Ntemis** [comment]
After submodule update
/home/demetris/Desktop/Development/DoubleDribbleDS/source/Cart.s:3:10: fatal error: equates.h: No such file or directory
    3 | #include "equates.h"
      |          ^~~~~~~~~~~
compilation terminated.

**Comment by FluBBaOfWard** [comment]
Fixed case in Cart.s

**Comment by Ntemis** [comment]
gtg
